job_name: golights
serial_port: /dev/tty.usbserial-A60080Ig
jenkins:
  host: localhost
  port: 8080

# Polling frequency in seconds.
polling_frequency: 3

light_codes:
  'blue': 1
  'blue_anime': 10
  'yellow': 2
  'yellow_anime': 20
  'red': 3
  'red_anime': 30
  'grey': 4
  'grey_anime':40
  'aborted': 4
  'aborted_anime': 40
  'disabled': 4
  'disabled_anime': 40
